import { useEffect, useMemo, useState } from "react";

type Product = { id: string; name: string; description: string; basePrice: number; promotionalPrice: number | null; minimumPromotionalQuantity: number | null; isAvailable: boolean; isFeatured: boolean; isDay?: boolean; imageUrl: string };
type Order = { id: string; publicCode: string; status: string; customerName: string; customerPhone: string; fulfillmentType: string; paymentMethod: string; total: number; createdAt: string; items: { productName: string; quantity: number }[]; customerNotes?: string };
type Store = { business: Record<string, unknown>; products: Product[]; orders: Order[] };
const money = (n: number) => n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const statuses = ["NOVO", "CONFIRMADO", "EM_PREPARO", "PRONTO", "SAIU_PARA_ENTREGA", "CONCLUIDO", "CANCELADO"];

export function AdminOperations({ onExit }: { onExit: () => void }) {
  const [code, setCode] = useState(sessionStorage.getItem("bf-admin") || ""); const [store, setStore] = useState<Store | null>(null); const [tab, setTab] = useState("dashboard"); const [feedback, setFeedback] = useState(""); const [search, setSearch] = useState(""); const headers = { "Content-Type": "application/json", "x-admin-code": code };
  const notify = (message: string) => { setFeedback(message); window.setTimeout(() => setFeedback(""), 2200); };
  const load = async (next = code) => { const r = await fetch("/api/admin/bootstrap", { headers: { "x-admin-code": next } }); if (!r.ok) throw new Error("Código de acesso inválido."); setStore(await r.json()); setCode(next); sessionStorage.setItem("bf-admin", next); };
  const product = async (item: Product, patch: Partial<Product>, message: string) => { const r = await fetch(`/api/admin/products/${item.id}`, { method: "PUT", headers, body: JSON.stringify({ ...item, ...patch }) }); if (!r.ok) return notify("Não foi possível salvar. Tente de novo."); await load(); notify(message); };
  const order = async (item: Order, status: string) => { const r = await fetch(`/api/admin/orders/${item.id}`, { method: "PUT", headers, body: JSON.stringify({ status }) }); if (!r.ok) return notify("Não foi possível atualizar o pedido."); await load(); notify("Pedido atualizado."); };
  const uploadPhoto = (item: Product, file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) return notify("Escolha uma imagem válida."); const reader = new FileReader(); reader.onload = () => product(item, { imageUrl: String(reader.result) }, "Foto atualizada."); reader.readAsDataURL(file); };
  if (!store) return <main className="admin-login"><button className="back" onClick={onExit}>← Sair</button><img className="brand-logo" src="/brand/brownieria-fortal-logo.png" alt="Brownieria Fortal" /><p className="eyebrow">OPERAÇÃO DIÁRIA</p><h1>Tudo pronto para produzir.</h1><p>Entre para atualizar sabores, acompanhar pedidos e manter o cardápio certo.</p><form onSubmit={e => { e.preventDefault(); load().catch(e => notify(e.message)); }}><input aria-label="Código de acesso" value={code} onChange={e => setCode(e.target.value)} placeholder="Código de acesso" /><button className="primary">Entrar no painel</button></form>{feedback && <p className="error">{feedback}</p>}</main>;
  const today = store.orders.filter(o => new Date(o.createdAt).toDateString() === new Date().toDateString()); const active = store.orders.filter(o => !["CONCLUIDO", "CANCELADO"].includes(o.status)); const revenue = today.filter(o => o.status !== "CANCELADO").reduce((s,o) => s + o.total, 0); const avg = today.length ? revenue / today.length : 0; const day = store.products.find(p => p.isDay) || store.products.find(p => p.isFeatured);
  return <main className="admin operations">{feedback && <div className="admin-toast">{feedback}</div>}<header><img className="brand-logo compact" src="/brand/brownieria-fortal-logo.png" alt="Brownieria Fortal" /><button className="text-button" onClick={onExit}>Sair</button></header><nav className="admin-tabs">{[["dashboard","Hoje"],["products","Sabores"],["promotions","Promoções"],["orders","Pedidos"],["production","Produção"],["settings","Ajustes"]].map(([id,label]) => <button className={tab===id?"active":""} onClick={() => setTab(id)} key={id}>{label}</button>)}</nav>
  {tab === "dashboard" && <section className="admin-content"><p className="eyebrow">OPERAÇÃO DE HOJE</p><h1>O que precisa da sua atenção.</h1><div className="metrics"><Metric label="Chegaram hoje" value={String(today.length)} /><Metric label="Aguardando" value={String(active.length)} /><Metric label="Receita estimada" value={money(revenue)} /><Metric label="Ticket médio" value={money(avg)} /></div><div className="op-card"><p>🍫 BROWNIE DO DIA</p><h2>{day?.name || "Escolha o destaque de hoje"}</h2><button className="primary" onClick={() => setTab("products")}>Alterar em segundos</button></div><div className="quick-actions"><button onClick={() => setTab("products")}>＋<span>Novo produto</span></button><button onClick={() => setTab("orders")}>📦<span>Pedidos</span></button><button onClick={() => setTab("production")}>◷<span>Produção</span></button><button onClick={() => setTab("settings")}>⚙<span>Ajustes</span></button></div><p className="subtle">Última atualização: agora. Esgotados: {store.products.filter(p => !p.isAvailable).map(p => p.name).join(", ") || "nenhum"}.</p></section>}
  {tab === "products" && <section className="admin-content"><p className="eyebrow">CARDÁPIO DE HOJE</p><h1>Disponibilidade em um toque.</h1><p className="subtle">As mudanças aparecem imediatamente para o cliente.</p><div className="admin-list">{store.products.map(p => <article className="op-product" key={p.id}><label className="photo-upload"><img src={p.imageUrl || "/images/brownie-hero-demo.png"} alt={`Foto de ${p.name}`} /><input type="file" accept="image/*" onChange={e => uploadPhoto(p, e.target.files?.[0])} /></label><div><h3>{p.name}</h3><p>{money(p.basePrice)}{p.promotionalPrice && ` · ${money(p.promotionalPrice)} a partir de ${p.minimumPromotionalQuantity}`}</p><div className="product-flags">{p.isDay && <b>Brownie do Dia</b>}{p.isFeatured && <b>Destaque</b>}</div></div><button className={p.isAvailable?"switch on":"switch"} aria-label={`Alterar disponibilidade de ${p.name}`} onClick={() => product(p,{isAvailable:!p.isAvailable},`${p.name} atualizado.`)}><i /></button><button className="day-toggle" onClick={() => Promise.all(store.products.filter(x => x.isDay && x.id !== p.id).map(x => product(x,{isDay:false},""))).then(() => product(p,{isDay:true},"Brownie do Dia atualizado."))}>☆ Dia</button></article>)}</div></section>}
  {tab === "promotions" && <Promotions products={store.products} onSave={product} />}
  {tab === "orders" && <OrderList orders={store.orders} search={search} setSearch={setSearch} onStatus={order} />}
  {tab === "production" && <section className="admin-content production"><p className="eyebrow">MODO PRODUÇÃO</p><h1>O que está na bancada.</h1>{active.length ? active.map(o => <article className="production-card" key={o.id}><span>{o.status.replaceAll("_"," ")}</span><h2>{o.publicCode}</h2><strong>{o.items.map(i => `${i.quantity} ${i.productName}`).join(" · ")}</strong><p>{o.fulfillmentType === "RETIRADA" ? "Retirada" : "Entrega"} · {new Date(o.createdAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</p>{o.customerNotes && <p>Obs.: {o.customerNotes}</p>}<select value={o.status} onChange={e => order(o,e.target.value)}>{statuses.map(s => <option key={s}>{s}</option>)}</select></article>) : <div className="empty"><h2>Nenhum pedido em produção.</h2><p>Quando chegarem, eles aparecem aqui em cartões grandes.</p></div>}</section>}
  {tab === "settings" && <Settings business={store.business} headers={headers} onSaved={() => { load(); notify("Configurações salvas."); }} />}</main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><b>{value}</b></div> }
function Promotions({ products, onSave }: { products: Product[]; onSave: (p: Product, patch: Partial<Product>, m: string) => void }) { return <section className="admin-content"><p className="eyebrow">PROMOÇÕES</p><h1>Preço por quantidade.</h1><p className="subtle">Ative somente condições reais que a equipe consegue cumprir.</p><div className="admin-list">{products.map(p => <article className="promo-editor" key={p.id}><b>{p.name}</b><label>Quantidade mínima<input type="number" value={p.minimumPromotionalQuantity || ""} onChange={e => onSave(p,{minimumPromotionalQuantity:e.target.value?Number(e.target.value):null},"Promoção atualizada.")} /></label><label>Preço promocional (R$)<input type="number" step=".01" value={p.promotionalPrice ? p.promotionalPrice/100 : ""} onChange={e => onSave(p,{promotionalPrice:e.target.value?Math.round(Number(e.target.value)*100):null},"Promoção atualizada.")} /></label></article>)}</div></section> }
function Settings({ business, headers, onSaved }: { business: Record<string, unknown>; headers: Record<string,string>; onSaved: () => void }) { const [draft,setDraft] = useState(business); return <section className="admin-content"><p className="eyebrow">CONFIGURAÇÕES</p><h1>Informações da Brownieria.</h1><form className="checkout-form" onSubmit={async e => { e.preventDefault(); await fetch("/api/admin/business",{method:"PUT",headers,body:JSON.stringify(draft)}); onSaved(); }}><label>Instagram<input value={String(draft.instagram||"")} onChange={e=>setDraft({...draft,instagram:e.target.value})} /></label><label>WhatsApp<input value={String(draft.whatsapp||"")} onChange={e=>setDraft({...draft,whatsapp:e.target.value})} /></label><label>Horário<input value={String(draft.hours||"")} onChange={e=>setDraft({...draft,hours:e.target.value})} /></label><label>Endereço<input value={String(draft.address||"")} onChange={e=>setDraft({...draft,address:e.target.value})} /></label><label>Mensagem após pedido<textarea value={String(draft.receivedMessage||"")} onChange={e=>setDraft({...draft,receivedMessage:e.target.value})} /></label><button className="primary">Salvar configurações</button></form></section> }
function OrderList({ orders, search, setSearch, onStatus }: { orders: Order[]; search: string; setSearch: (v:string)=>void; onStatus: (o: Order, s: string) => void }) { const found = useMemo(() => orders.filter(o => `${o.publicCode} ${o.customerName} ${o.customerPhone}`.toLowerCase().includes(search.toLowerCase())), [orders,search]); return <section className="admin-content"><p className="eyebrow">PEDIDOS</p><h1>Organize sem procurar.</h1><input className="order-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por código, nome ou telefone" /><div className="admin-list">{found.map(o => <article className="order-card" key={o.id}><div><span className="status">{o.status.replaceAll("_"," ")}</span><h3>{o.publicCode} · {o.customerName}</h3><p>{o.customerPhone} · {o.items.map(i=>`${i.quantity}× ${i.productName}`).join(", ")}</p><strong>{money(o.total)}</strong></div><select value={o.status} onChange={e => onStatus(o,e.target.value)}>{statuses.map(s => <option key={s}>{s}</option>)}</select></article>)}</div></section> }
