import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Clipboard, Minus, Plus, ShoppingBag } from "lucide-react";
import { calculateLinePrice, type PricingProduct } from "./lib/pricing";
import { productImageSrc } from "./lib/media";
import { formatCurrency } from "./lib/format";
import { AdminOperations } from "./AdminOperations";

type Product = PricingProduct & { id: string; slug: string; name: string; description: string; category: string; imageUrl: string; isActive: boolean; isAvailable: boolean; isFeatured: boolean; isDay?: boolean; displayOrder: number; ingredients?: string; allergens?: string; updatedAt: string };
type Business = { name: string; tagline: string; description: string; phone: string; whatsapp: string; address: string; hours: string; instagram: string; pickupEnabled: boolean; deliveryEnabled: boolean; paymentMethods: string[]; deliveryFee: number; receivedMessage: string; availabilityNotice: string; isDemo: boolean };
type CartLine = { product: Product; quantity: number };
type Order = { id: string; publicCode: string; status: string; subtotal: number; discount: number; deliveryFee: number; total: number; items: { productName: string; quantity: number; unitPrice: number; totalPrice: number }[]; createdAt: string; fulfillmentType: string; paymentMethod: string };
async function api<T>(url: string, options?: RequestInit): Promise<T> { const response = await fetch(url, { headers: { "Content-Type": "application/json", ...(options?.headers || {}) }, ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Não foi possível concluir a ação."); return data; }
function BrandLogo({ compact = false }: { compact?: boolean }) { return <img className={compact ? "brand-logo compact" : "brand-logo"} src="/brand/brownieria-fortal-logo.png" alt="Brownieria Fortal" />; }

export default function App() {
  const [business, setBusiness] = useState<Business | null>(null); const [products, setProducts] = useState<Product[]>([]); const [cart, setCart] = useState<CartLine[]>([]);
  const [screen, setScreen] = useState<"home" | "menu" | "product" | "cart" | "checkout" | "confirmed" | "admin">("home"); const [selected, setSelected] = useState<Product | null>(null); const [order, setOrder] = useState<Order | null>(null); const [notice, setNotice] = useState("");
  const refresh = async () => { const [b, p] = await Promise.all([api<Business>("/api/public/business"), api<Product[]>("/api/public/menu")]); setBusiness(b); setProducts(p); };
  useEffect(() => { refresh().catch(error => setNotice(error.message)); }, []);
  const add = (product: Product, quantity = 1) => { if (!product.isAvailable) return; setCart(lines => { const found = lines.find(line => line.product.id === product.id); return found ? lines.map(line => line.product.id === product.id ? { ...line, quantity: line.quantity + quantity } : line) : [...lines, { product, quantity }]; }); setNotice(`${product.name} adicionado ao pedido.`); };
  const change = (id: string, quantity: number) => setCart(lines => quantity < 1 ? lines.filter(line => line.product.id !== id) : lines.map(line => line.product.id === id ? { ...line, quantity } : line));
  const summary = useMemo(() => cart.reduce((acc, line) => { const price = calculateLinePrice(line.product, line.quantity); return { subtotal: acc.subtotal + price.total, discount: acc.discount + price.discount }; }, { subtotal: 0, discount: 0 }), [cart]);
  if (!business) return <main className="loading">Carregando cardápio…</main>;
  if (screen === "admin") return <AdminOperations onExit={() => { setScreen("home"); refresh(); }} />;
  return <main className="app-shell"><header className="public-header"><button className="brand" onClick={() => setScreen("home")} aria-label="Ir para o início"><BrandLogo compact /></button><button className="cart-button" onClick={() => setScreen("cart")} aria-label="Abrir pedido"><ShoppingBag size={19} />{cart.length > 0 && <b>{cart.reduce((n, l) => n + l.quantity, 0)}</b>}</button></header>{notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    {screen === "home" && <Home business={business} products={products} onMenu={() => setScreen("menu")} onAdmin={() => setScreen("admin")} onProduct={p => { setSelected(p); setScreen("product"); }} onAdd={add} />}
    {screen === "menu" && <Menu products={products} onBack={() => setScreen("home")} onProduct={p => { setSelected(p); setScreen("product"); }} onAdd={add} />}
    {screen === "product" && selected && <ProductDetail product={selected} recommendations={products.filter(p => p.isFeatured && p.id !== selected.id && p.isAvailable).slice(0, 2)} onBack={() => setScreen("menu")} onAdd={add} />}
    {screen === "cart" && <Cart lines={cart} subtotal={summary.subtotal} discount={summary.discount} onBack={() => setScreen("menu")} onChange={change} onCheckout={() => setScreen("checkout")} />}
    {screen === "checkout" && <Checkout business={business} lines={cart} summary={summary} onBack={() => setScreen("cart")} onDone={created => { setOrder(created); setCart([]); setScreen("confirmed"); }} />}
    {screen === "confirmed" && order && <Confirmation order={order} message={business.receivedMessage} onMenu={() => setScreen("menu")} />}
  </main>;
}

function Home({ products, onMenu, onAdmin, onProduct, onAdd }: { business: Business; products: Product[]; onMenu: () => void; onAdmin: () => void; onProduct: (p: Product) => void; onAdd: (p: Product) => void }) { const day = products.find(p => p.slug === "brigadeiro") || products[0]; return <><section className="hero"><div><p className="eyebrow">PREPARADOS ARTESANALMENTE HOJE</p><h1>O brownie que conquista na primeira mordida.</h1><p>Feitos em pequenos lotes para garantir casquinha, recheio e muito chocolate de verdade.</p><div className="hero-actions"><button className="primary" onClick={onMenu}>Escolher meus brownies <ChevronRight size={18} /></button><button className="secondary" onClick={onMenu}>Ver cardápio</button></div></div><figure className="hero-photo"><img src={productImageSrc(day ?? {})} alt="Foto demonstrativa de brownie de chocolate com recheio cremoso" /><figcaption>Imagem demonstrativa — aguardando foto oficial</figcaption></figure></section><section className="day-feature"><p>🍫 BROWNIE DO DIA</p><h2>Hoje o destaque é {day?.name}</h2><span>Produzido nesta manhã · quantidade limitada</span><button onClick={() => day && onProduct(day)}>Conhecer o sabor</button></section><section className="section story"><p className="eyebrow">A NOSSA RECEITA DE TODO DIA</p><h2>Chocolate de verdade. Feito com carinho.</h2><p>Ingredientes selecionados, produção diária e aquela pausa gostosa que melhora o dia inteiro.</p></section><section className="section"><div className="section-title"><div><p className="eyebrow">MAIS PEDIDOS HOJE</p><h2>Quem experimenta volta.</h2></div><button className="text-button" onClick={onMenu}>Ver todos</button></div><div className="product-grid">{products.filter(p => p.isFeatured).slice(0, 3).map(p => <ProductCard key={p.id} product={p} onClick={() => onProduct(p)} onAdd={() => onAdd(p)} />)}</div></section><section className="collections"><p className="eyebrow">PARA CADA VONTADE</p><h2>Uma caixa para dividir. Ou não.</h2><p>Em breve, monte combinações para presentear, compartilhar ou guardar só para você.</p><button className="secondary" onClick={onMenu}>Explorar sabores</button></section><section className="social-proof"><strong>Feitos em pequenos lotes, todos os dias.</strong><span>Números e avaliações reais serão exibidos aqui após validação da Brownieria.</span></section><section className="how"><p className="eyebrow">É MUITO SIMPLES ❤️</p><h2>Seu momento doce está a poucos passos.</h2><p>1. Escolha seus brownies. &nbsp; 2. Monte seu pedido. &nbsp; 3. Receba fresquinho.</p></section><footer><span>Brownieria Fortal <em>• demonstração</em></span><button onClick={onAdmin}>Área da equipe</button></footer></> }
function Menu({ products, onBack, onProduct, onAdd }: { products: Product[]; onBack: () => void; onProduct: (p: Product) => void; onAdd: (p: Product) => void }) { const ordered = [...products].sort((a,b) => Number(b.slug === "brigadeiro") - Number(a.slug === "brigadeiro") || Number(b.isFeatured) - Number(a.isFeatured) || Number(b.isAvailable) - Number(a.isAvailable) || a.displayOrder - b.displayOrder); return <section className="section page menu-page"><Back onClick={onBack} /><p className="eyebrow">CARDÁPIO ATUALIZADO</p><h1>Escolha seu momento doce.</h1><p className="subtle">Produzidos em pequenos lotes. Sabores disponíveis aparecem primeiro.</p><div className="product-grid menu-grid">{ordered.map(p => <ProductCard key={p.id} product={p} isDay={p.slug === "brigadeiro"} onClick={() => onProduct(p)} onAdd={() => onAdd(p)} />)}</div></section> }
function ProductCard({ product, isDay = false, onClick, onAdd }: { key?: string; product: Product; isDay?: boolean; onClick: () => void; onAdd?: () => void }) { const promo = product.promotionalPrice && product.minimumPromotionalQuantity; return <article className={`product-card ${!product.isAvailable ? "sold-out" : ""}`}><button className="product-main" onClick={onClick}><div className="product-photo"><img loading="lazy" decoding="async" src={productImageSrc(product)} alt={`Imagem demonstrativa de ${product.name}`} />{isDay && <span className="day-badge">Brownie do Dia</span>}</div><div className="product-copy"><p className="product-category">{product.category}</p><h3>{product.name}</h3><p>{product.description}</p>{promo && <small className="promo">{formatCurrency(product.promotionalPrice!)} cada a partir de {product.minimumPromotionalQuantity} un.</small>}<strong>{formatCurrency(product.basePrice)}</strong></div></button><div className="product-footer"><span className={product.isAvailable ? "available" : "unavailable"}>{product.isAvailable ? "Disponível hoje" : "Esgotado hoje"}</span>{onAdd && <button disabled={!product.isAvailable} className="add-icon" onClick={onAdd} aria-label={`Adicionar ${product.name}`}>{product.isAvailable ? <Plus size={18} /> : "—"}</button>}</div></article> }
function ProductDetail({ product, recommendations, onBack, onAdd }: { product: Product; recommendations: Product[]; onBack: () => void; onAdd: (p: Product, q: number) => void }) { const [quantity, setQuantity] = useState(1); const price = calculateLinePrice(product, quantity); return <section className="section page product-page"><Back onClick={onBack} /><figure className="product-hero-photo"><img src={productImageSrc(product)} alt={`Imagem demonstrativa de ${product.name}`} /><figcaption>Imagem demonstrativa — aguardando foto oficial</figcaption></figure><p className="eyebrow">FEITO ARTESANALMENTE</p><h1>{product.name}</h1><p className="detail-description">{product.description}</p><strong className="big-price">{formatCurrency(price.unitPrice)}</strong>{product.promotionalPrice && <p className="promo">Quanto mais brownies, melhor o preço: {formatCurrency(product.promotionalPrice)} cada a partir de {product.minimumPromotionalQuantity} unidades.</p>}<Info label="Ingredientes" value={product.ingredients} /><Info label="Alergênicos" value={product.allergens} /><div className="quantity"><button aria-label="Diminuir quantidade" onClick={() => setQuantity(q => Math.max(1, q - 1))}><Minus size={18} /></button><b>{quantity}</b><button aria-label="Aumentar quantidade" onClick={() => setQuantity(q => q + 1)}><Plus size={18} /></button></div><button disabled={!product.isAvailable} className="primary wide" onClick={() => onAdd(product, quantity)}>{product.isAvailable ? `Adicionar ao pedido · ${formatCurrency(price.total)}` : "Esgotado hoje"}</button><RelatedProducts products={recommendations} /></section> }
function RelatedProducts({ products }: { products: Product[] }) { return products.length ? <section className="related"><p className="eyebrow">COMBINA COM</p><h2>Outros favoritos da Brownieria</h2><div>{products.map(product => <span key={product.id}>{product.name}</span>)}</div></section> : null }
function Cart({ lines, subtotal, discount, onBack, onChange, onCheckout }: { lines: CartLine[]; subtotal: number; discount: number; onBack: () => void; onChange: (id: string, q: number) => void; onCheckout: () => void }) { const promotionHint = lines.find(line => line.product.minimumPromotionalQuantity && line.quantity < line.product.minimumPromotionalQuantity); return <section className="section page cart-page"><Back onClick={onBack} /><p className="eyebrow">SEU PEDIDO</p><h1>Sua caixa está quase pronta.</h1>{lines.length === 0 ? <div className="empty"><ShoppingBag /><h2>Ainda não tem brownie por aqui.</h2><p>Escolha seus sabores favoritos no cardápio.</p><button className="primary" onClick={onBack}>Ver sabores</button></div> : <>{promotionHint && <p className="cart-nudge">Faltam {promotionHint.product.minimumPromotionalQuantity! - promotionHint.quantity} brownies de {promotionHint.product.name} para aproveitar o preço por quantidade.</p>}<div className="cart-list">{lines.map(line => { const price = calculateLinePrice(line.product, line.quantity); return <article className="cart-line" key={line.product.id}><img src={productImageSrc(line.product)} alt="Imagem demonstrativa" /><div><h3>{line.product.name}</h3><p>{formatCurrency(price.unitPrice)} cada</p><div className="quantity small"><button aria-label="Diminuir" onClick={() => onChange(line.product.id, line.quantity - 1)}><Minus size={14} /></button><b>{line.quantity}</b><button aria-label="Aumentar" onClick={() => onChange(line.product.id, line.quantity + 1)}><Plus size={14} /></button></div></div><strong>{formatCurrency(price.total)}</strong></article>; })}</div><Totals subtotal={subtotal} discount={discount} deliveryFee={0} /><button className="primary wide" onClick={onCheckout}>Continuar pedido <ChevronRight size={18} /></button><button className="link-danger" onClick={() => lines.forEach(l => onChange(l.product.id, 0))}>Limpar pedido</button></>}</section> }
function Checkout({ business, lines, summary, onBack, onDone }: { business: Business; lines: CartLine[]; summary: { subtotal: number; discount: number }; onBack: () => void; onDone: (order: Order) => void }) { const [fulfillment, setFulfillment] = useState(business.pickupEnabled ? "RETIRADA" : "ENTREGA"); const [payment, setPayment] = useState("PIX"); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const deliveryFee = fulfillment === "ENTREGA" ? business.deliveryFee : 0;
 const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); try { const created = await api<Order>("/api/public/orders", { method: "POST", body: JSON.stringify({ items: lines.map(l => ({ productId: l.product.id, quantity: l.quantity })), customerName: form.get("name"), customerPhone: form.get("phone"), fulfillmentType: fulfillment, deliveryAddress: form.get("address"), reference: form.get("reference"), customerNotes: form.get("notes"), paymentMethod: payment, changeFor: form.get("change") }) }); onDone(created); } catch (e) { setError(e instanceof Error ? e.message : "Erro ao criar pedido."); } finally { setLoading(false); } };
 return <section className="section page checkout-page"><Back onClick={onBack} /><p className="eyebrow">FINALIZAR PEDIDO</p><h1>Para quem é essa delícia?</h1><p className="subtle">Só pedimos o necessário para preparar seu pedido com cuidado.</p><form className="checkout-form" onSubmit={submit}><label>Seu nome<input required name="name" maxLength={100} placeholder="Como podemos te chamar?" /></label><label>Seu WhatsApp<input required name="phone" inputMode="tel" maxLength={30} placeholder="(85) 9 0000-0000" /></label><fieldset><legend>Como prefere receber?</legend><div className="choice-row">{business.pickupEnabled && <button type="button" className={fulfillment === "RETIRADA" ? "choice active" : "choice"} onClick={() => setFulfillment("RETIRADA")}>Retirada</button>}{business.deliveryEnabled && <button type="button" className={fulfillment === "ENTREGA" ? "choice active" : "choice"} onClick={() => setFulfillment("ENTREGA")}>Entrega</button>}</div></fieldset>{fulfillment === "ENTREGA" && <><label>Onde entregamos?<input required name="address" maxLength={300} placeholder="Rua, número e bairro" /></label><label>Referência<input name="reference" maxLength={200} placeholder="Opcional" /></label></>}<fieldset><legend>Como você prefere pagar?</legend><div className="choice-row">{business.paymentMethods.map(method => <button type="button" key={method} className={payment === method ? "choice active" : "choice"} onClick={() => setPayment(method)}>{method === "A_COMBINAR" ? "A combinar" : method}</button>)}</div></fieldset>{payment === "DINHEIRO" && <label>Troco para qual valor?<input name="change" inputMode="decimal" placeholder="Opcional" /></label>}<label>Algum detalhe importante?<textarea name="notes" maxLength={1000} placeholder="Opcional" /></label><Totals subtotal={summary.subtotal} discount={summary.discount} deliveryFee={deliveryFee} />{error && <p className="error">{error}</p>}<button className="primary wide" disabled={loading}>{loading ? "Enviando…" : "Confirmar pedido"}</button></form></section> }
function Confirmation({ order, message, onMenu }: { order: Order; message: string; onMenu: () => void }) { const copy = () => navigator.clipboard?.writeText(`${order.publicCode} — ${formatCurrency(order.total)}`); return <section className="section page confirmation"><div className="check"><Check /></div><p className="eyebrow">PEDIDO RECEBIDO</p><h1>Que delícia, está confirmado.</h1><p>{message || "Nossa equipe irá preparar seu pedido com todo cuidado."}</p><div className="code"><span>Número do pedido</span><strong>{order.publicCode}</strong><button onClick={copy}><Clipboard size={15} /> Copiar código</button></div><div className="next-steps"><b>Próximos passos</b><p>Você escolheu {order.fulfillmentType === "RETIRADA" ? "retirada" : "entrega"} e pagamento {order.paymentMethod === "A_COMBINAR" ? "a combinar" : order.paymentMethod}. A equipe confirmará os detalhes em breve.</p></div><Totals subtotal={order.subtotal} discount={order.discount} deliveryFee={order.deliveryFee} /><button className="primary wide" onClick={onMenu}>Voltar ao cardápio</button></section> }
function Totals({ subtotal, discount, deliveryFee }: { subtotal: number; discount: number; deliveryFee: number }) { return <div className="totals"><p><span>Subtotal</span><b>{formatCurrency(subtotal + discount)}</b></p>{discount > 0 && <p className="saving"><span>Economia</span><b>− {formatCurrency(discount)}</b></p>}{deliveryFee > 0 && <p><span>Entrega</span><b>{formatCurrency(deliveryFee)}</b></p>}<p className="total"><span>Total</span><b>{formatCurrency(subtotal + deliveryFee)}</b></p></div> }
function Info({ label, value }: { label: string; value?: string }) { return value ? <div className="info"><b>{label}</b><p>{value}</p></div> : null; }
function Back({ onClick }: { onClick: () => void }) { return <button className="back" onClick={onClick}><ArrowLeft size={18} /> Voltar</button> }
